services:
  db:
    image: postgres:16
    container_name: bd-ong-voluntarios
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backendong

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-ong
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - uploads_data:${APP_UPLOAD_DIR}
    ports:
      - "8080:8080"
    networks:
      - backendong
    restart: always


networks:
  backendong:
    driver: bridge

volumes:
  postgres_data:
  uploads_data: