

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: q1w2e3
    ports:
      - 5431:5432
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: backend-ong
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/app_db
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: q1w2e3
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - postgres

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
