spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_FORMAT_SQL:true}
        dialect: ${SPRING_JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          ssl:
            enable: ${MAIL_SMTP_SSL_ENABLE:true}
    default-encoding: UTF-8
    default-from: ${MAIL_DEFAULT_FROM}

server:
  port: ${SERVER_PORT:8080}

app:
  upload:
    dir: ${APP_UPLOAD_DIR}
  base-url: ${APP_BASE_URL}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

api:
  security:
    token:
      secret: ${API_SECURITY_TOKEN_SECRET}
