name: CI/CD Backend ONG v2

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout / verificacao codigo
        uses: actions/checkout@v4

      - name: Login No DockerHub
        uses: docker/login-action@v3
        with:
        username: ${{ secrests.DOCKERHUB_USERNAME }}
        password: ${{ secrests.DOCKERHUB_TOKEN }}

      - name:  Build e Push da imagem para o docker DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ryanmosc/backend-ong:latest
            ryanmosc/backend-ong:${{ github.sha }}

      - name: Deploy na vps
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrests.VPS_HOST }}
          username: ${{ secrests.VPS_USER }}
          key: ${{ secrests.VPS_SSH_KEY }}
          script: |
            cd /opt/backend
            docker compose down -v
            docker compose pull
            dokcer compose up -d
